# v1.10 develop version  
title: 虚无之下，皆为毁灭 - 破碎宇宙官方网站

# Menu Config
menus: 
  流浪虚无: categories/衍生小说/流浪虚无
  第二者: categories/衍生小说/第二者
  杀手查莉: categories/衍生小说/杀手查莉

# Footer Link
links:
  Turbo Flint: "https://turboflint.cn/"
  Blog: "https://turboflint.cn/posts"
  Github: "https://github.com/ericlee517"
  Copyright: "https://docs.turboflint.cn/others/broken-copyright"

# Authors Config Please Read: 
authors:
  Eric:
    name: Eric
    avatar_url: https://static.turboflint.cn/image/ericlee.png
    type: official
    bio: 破碎宇宙创作者
  BroKen_Photo:
    name: BroKen_Photo
    avatar_url: https://static.turboflint.cn/image/horizon.jpg
    type: official
    bio: 破碎宇宙官方作者
  UNKNOW:
    name: UNKNOW
    avatar_url: https://static.turboflint.cn/image/user.svg
    type: official
    bio: 破碎宇宙内容发布BOT
  Turbo_Flint:
    name: Turbo_Flint
    avatar_url: https://static.turboflint.cn/image/flint_logo.jpg
    type: official
    bio: 涡轮火石新闻发布

# 此部分请阅读文档：
i18n: false
basic-card: true
all-articles: true
animated: true
team-members: true

# System Config. Please Do Not Modify!
version: 1.11_Release